### ISSUE TITLE
empty page in component

### ISSUE THREAD

**Issue by zebrafilm** [webfonts/Web-Fonts#1]
Using J1.7.3 and webfont 2.0 o a windows server.
After installing both plugin and component, the component shows an empty page.....
Can't find any docs about how to proceed or if this is normal.

**Comment by webfonts** [comment]
I can confirm that this is occurring on windows shared hosts and am looking into it.

**Comment by webfonts** [comment]
The Fonts.com portion of the extension uses Curl to call its API.  Microsoft IIS servers don't ship with a list of current certificates (Certificate Bundle) in their PHP package and this causes CURL to fail when accessing a secure site, like the Fonts.com API.  I've corrected this but haven't pushed it to the repo yet.  I will close this issue as soon as it is integrated (though potentially after Turkey day).

http://richardwarrender.com/2007/05/the-secret-to-curl-in-php-on-windows/

**Comment by zebrafilm** [comment]
Thanks for the updates, and good to know you found the problem.
I was planning to test it for a few website, so please let me know when
you are done with your Turkey.
Happy holidays.

Bastiaan

On 24-11-11 05:25, "John Hooley"
<reply+i-2317745-b0048f2290e282778f9396413fa0c1b3d8ce5812-1212943@reply.git
hub.com> wrote:
