### ISSUE TITLE
Addition of !important in css — can it be control?

### ISSUE THREAD

**Issue by Chacapamac** [webfonts/Web-Fonts#10]
I see that you adding the “!important” at the end of the css line....

It will be cool to have some kind of control if you want to add it or not...

My suggestion is to have a tick box with !important selected by default and can be unselected — !important can be problematic in certain situations and you got no easy way to turn it off...

Just a suggestion !

Excellent Work... I love it!

**Comment by webfonts** [comment]
Hey Chapamac,

Great suggestion and thanks for your feedback on this and the other items.
I'm dealing with a medical issue and won't be able to look into these until
after July 9th, but will post here once I've had a chance to inspect them
in detail.

Sincerely,

John

On Fri, Jun 29, 2012 at 3:29 PM, Chacapamac <
reply@reply.github.com

> wrote:
> 
> I see that you adding the “!important” at the end of the css line....
> 
> It will be cool to have some kind of control if you want to add it or
> not...
> 
> My suggestion is to have a tick box with !important selected by default
> and can be unselected — !important can be problematic in certain situations
> and you got no easy way to turn it off...
> 
> Just a suggestion !
> 
> Excellent Work... I love it!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/webfonts/Web-Fonts/issues/10

## 

John Hooley
Blue Bridge Development
(503) 893-9181 https://www.google.com/voice#phones
http://bluebridgedev.com

**Comment by webfonts** [comment]
Hey Chapamac,

What would you think about removing it altogether?  Originally, !important was added because I was using a common convention in Joomla that did not guarantee that the stylesheet calls would be at the bottom of the head element in the document and there was a chance that a template or other extension's stylesheet might overwrite it.  Since then, I changed it so that it always sinks to the bottom of the head element.

J

**Comment by Chacapamac** [comment]
Yes, I think, remove the !important will be better. And it can be added manually if needed - but to make it a default and having the choice to remove it is maybe good to.... I need to return into the testing of your Webfont — Personnaly I think your addon is fantastic really flexible. Bravo

I just add My “Excellent” Review on the JED — should be there soon...

**Comment by webfonts** [comment]
Hey Chacapamac, thanks for your review and taking the time to write it, I appreciate it.  :)

**Comment by webfonts** [comment]
Updated downloads with revised plugin that does not add !important to head declaration.

**Comment by Chacapamac** [comment]
I just have to reinstall over — I will not loose my settings?

**Comment by webfonts** [comment]
That's correct, just install it through the extension manager and it will
not affect any fonts you have selected beyond removing the !important from
the declaration.

**Comment by Chacapamac** [comment]
Thanks — Work perfect
 — You should add a version number to your add-on (easier for us)
