### ISSUE TITLE
Web fonts not accessible

### ISSUE THREAD

**Issue by designmedia** [webfonts/Web-Fonts#12]
Hello, I have the plugin installed but they do not work when I add a selector. What am I doing wrong?

**Comment by webfonts** [comment]
Have you enabled the plugin?

For Fonts.com, it can take a few minutes while the CDN is updated with your
new selectors (the longest I've waited is around 10 minutes, but usually
it's much faster than that).

On Tue, Aug 7, 2012 at 12:20 PM, designmedia notifications@github.comwrote:

> Hello, I have the plugin installed but they do not work when I add a
> selector. What am I doing wrong?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/webfonts/Web-Fonts/issues/12.

## 

John Hooley
Blue Bridge Development
(503) 893-9181 https://www.google.com/voice#phones
http://bluebridgedev.com

**Comment by designmedia** [comment]
Yes - you helped me install it...

**Comment by webfonts** [comment]
Margaret,

It is working.  You'll notice your testimonials are now styled with one of
your fonts.

The problem you're running into is that many of your elements are assigned
styles through your WYSIWYG editor, making it very difficult for a CSS
selector to overwrite that style.

For example, here is some markup:

<p align="right" style="text-align: left;">
<span style="font-family: impact,chicago; font-size: 18pt; color: #bd0606;">
<span style="line-height: 115%;">Per­for­mance</span>
</span>
<span style="font-size: 14pt; line-height: 115%; font-family: 'Brush Script
MT';"></span>
</p>


You will find it impossible to set a style for this paragraph element
because your WYSIWYG editor already set font families of impact, chicago at
the lowest level.  In this case, the only possible way to change the font
is through your WYSIWYG editor.  To use CSS, you need to remove this low
level styling.

This is something that can be assigned a font-family with the extension or
a stylesheet:

<p>Performance</p>


Using firebug, we could see the needed styling might be something like:

#main p

It's important that you understand how CSS and XHtml work to use the
extension effectively.

Hope this helps!

J

On Tue, Aug 7, 2012 at 12:34 PM, Margaret Aquino
notifications@github.comwrote:

> Yes - you helped me install it...
> 
> On 8/7/2012 2:26 PM, John Hooley wrote:
> 
> > Have you enabled the plugin?
> > 
> > For Fonts.com, it can take a few minutes while the CDN is updated with
> > your
> > new selectors (the longest I've waited is around 10 minutes, but usually
> > it's much faster than that).
> > 
> > On Tue, Aug 7, 2012 at 12:20 PM, designmedia
> > notifications@github.comwrote:
> > 
> > > Hello, I have the plugin installed but they do not work when I add a
> > > selector. What am I doing wrong?
> > > 
> > > —
> > > Reply to this email directly or view it on
> > > GitHubhttps://github.com/webfonts/Web-Fonts/issues/12.
> > 
> > ## 
> > 
> > John Hooley
> > Blue Bridge Development
> > (503) 893-9181 https://www.google.com/voice#phones
> > http://bluebridgedev.com
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/webfonts/Web-Fonts/issues/12#issuecomment-7562261.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/webfonts/Web-Fonts/issues/12#issuecomment-7562504.

## 

John Hooley
Blue Bridge Development
(503) 893-9181 https://www.google.com/voice#phones
http://bluebridgedev.com

**Comment by designmedia** [comment]
Thank you so much for the help John!...I was going crazy with this...
I really appreciate your time.

Margaret

**Comment by webfonts** [comment]
No problem, I hope you're able to get the fonts working where you want
them. :)

J

On Tue, Aug 7, 2012 at 1:33 PM, Margaret Aquino notifications@github.comwrote:

> Thank you so much for the help John!...I was going crazy with this...
> I really appreciate your time.
> 
> Margaret
> 
> On 8/7/2012 3:16 PM, John Hooley wrote:
> 
> > Margaret,
> > 
> > It is working. You'll notice your testimonials are now styled with one of
> > your fonts.
> > 
> > The problem you're running into is that many of your elements are
> > assigned
> > styles through your WYSIWYG editor, making it very difficult for a CSS
> > selector to overwrite that style.
> > 
> > For example, here is some markup:
> > 
> > <p align="right" style="text-align: left;">
> > <span style="font-family: impact,chicago; font-size: 18pt; color:
> > #bd0606;">
> > <span style="line-height: 115%;">Per­for­mance</span>
> > </span>
> > <span style="font-size: 14pt; line-height: 115%; font-family: 'Brush
> > Script
> > MT';"></span>
> > </p>
> > 
> > 
> > You will find it impossible to set a style for this paragraph element
> > because your WYSIWYG editor already set font families of impact,
> > chicago at
> > the lowest level. In this case, the only possible way to change the font
> > is through your WYSIWYG editor. To use CSS, you need to remove this low
> > level styling.
> > 
> > This is something that can be assigned a font-family with the
> > extension or
> > a stylesheet:
> > 
> > <p>Performance</p>
> > 
> > 
> > Using firebug, we could see the needed styling might be something like:
> > 
> > #main p
> > 
> > It's important that you understand how CSS and XHtml work to use the
> > extension effectively.
> > 
> > Hope this helps!
> > 
> > J
> > 
> > On Tue, Aug 7, 2012 at 12:34 PM, Margaret Aquino
> > notifications@github.comwrote:
> > 
> > > Yes - you helped me install it...
> > > 
> > > On 8/7/2012 2:26 PM, John Hooley wrote:
> > > 
> > > > Have you enabled the plugin?
> > > > 
> > > > For Fonts.com, it can take a few minutes while the CDN is updated
> > > > with
> > > > your
> > > > new selectors (the longest I've waited is around 10 minutes, but
> > > > usually
> > > > it's much faster than that).
> > > > 
> > > > On Tue, Aug 7, 2012 at 12:20 PM, designmedia
> > > > notifications@github.comwrote:
> > > > 
> > > > > Hello, I have the plugin installed but they do not work when I
> > > > > add a
> > > > > selector. What am I doing wrong?
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on
> > > > > GitHubhttps://github.com/webfonts/Web-Fonts/issues/12.
> > > > 
> > > > ## 
> > > > 
> > > > John Hooley
> > > > Blue Bridge Development
> > > > (503) 893-9181 https://www.google.com/voice#phones
> > > > http://bluebridgedev.com
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > 
> > > > https://github.com/webfonts/Web-Fonts/issues/12#issuecomment-7562261.
> > > 
> > > —
> > > Reply to this email directly or view it on
> > > GitHub<
> > > https://github.com/webfonts/Web-Fonts/issues/12#issuecomment-7562504>.
> > 
> > ## 
> > 
> > John Hooley
> > Blue Bridge Development
> > (503) 893-9181 https://www.google.com/voice#phones
> > http://bluebridgedev.com
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/webfonts/Web-Fonts/issues/12#issuecomment-7563692.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/webfonts/Web-Fonts/issues/12#issuecomment-7564141.

## 

John Hooley
Blue Bridge Development
(503) 893-9181 https://www.google.com/voice#phones
http://bluebridgedev.com
