### ISSUE TITLE
Web Fonts works with #art-main, not with heading

### ISSUE THREAD

**Issue by sd19** [webfonts/Web-Fonts#14]
Hi,

I installed Web Fonts on my website. The chosen font seems to work with selector '#art-main' but not with heading 1. For heading 1, I chose 'h1' as selector. but nothing happened. My template is created in Artisteer and I'm using JC Editor. I could use some help.

Thanks in advance.

**Comment by webfonts** [comment]
Hi,

Sorry to hear you're having issues.  Can you send a link to a page with the
h1 issue?  I think it's likely another style in your stylesheet is
over-writing it.

Sincerely,

John

On Tue, Oct 2, 2012 at 5:13 PM, sd19 notifications@github.com wrote:

> Hi,
> 
> I installed Web Fonts on my website. The chosen font seems to work with
> selector '#art-main' but not with heading 1. For heading 1, I chose 'h1' as
> selector. but nothing happened. My template is created in Artisteer and I'm
> using JC Editor. I could use some help.
> 
> Thanks in advance.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/webfonts/Web-Fonts/issues/14.

## 

John Hooley
Blue Bridge Development
(503) 893-9181 https://www.google.com/voice#phones
http://bluebridgedev.com

**Comment by sd19** [comment]
Hi,

The problem is already solved! Yesterday, I tried another selector than
'h1', thinking that maybe another selector was combined to heading 1. It
turned out that I always used a wrong selector :)

Thanks for your help anyway.

Sincerely,

Steffie

---

Van: John Hooley [mailto:notifications@github.com] 
Verzonden: woensdag 3 oktober 2012 1:39
Aan: webfonts/Web-Fonts
CC: Steffie Docx
Onderwerp: Re: [Web-Fonts] Web Fonts works with #art-main, not with
heading (#14)

Hi, 

Sorry to hear you're having issues. Can you send a link to a page with
the 
h1 issue? I think it's likely another style in your stylesheet is 
over-writing it. 

Sincerely, 

John 

On Tue, Oct 2, 2012 at 5:13 PM, sd19 notifications@github.com wrote: 

> Hi, 
> 
> I installed Web Fonts on my website. The chosen font seems to work
> with 
> selector '#art-main' but not with heading 1. For heading 1, I chose
> 'h1' as 
> selector. but nothing happened. My template is created in Artisteer
> and I'm 
> using JC Editor. I could use some help. 
> 
> Thanks in advance. 
> - 
>   Reply to this email directly or view it on
>   GitHubhttps://github.com/webfonts/Web-Fonts/issues/14. 

## 

John Hooley 
Blue Bridge Development 
(503) 893-9181 https://www.google.com/voice#phones 
http://bluebridgedev.com 

## 

Reply to this email directly or view it on GitHub
https://github.com/webfonts/Web-Fonts/issues/14#issuecomment-9091176 .

<https://github.com/notifications/beacon/J6T91GIPIyhU-8ti4GCGP1fQqsLKOu0
qZAGLO0JtRCaHUZK2e0h1-w1s-iMHezFe.gif>
