### ISSUE TITLE
question marks

### ISSUE THREAD

**Issue by codewaresolutions** [webfonts/Web-Fonts#15]
Is web fonts joomla extension compatible with IE 8?
When browsing on IE 8, there are some question mark shown throughout the text - the issue does not occur with other browsers.

**Comment by webfonts** [comment]
Hi,

Sounds like a character encoding issue. Can you post a link to an example?

Thanks,

J

On Fri, Oct 5, 2012 at 5:33 AM, codewaresolutions
notifications@github.comwrote:

> Is web fonts joomla extension compatible with IE 8?
> When browsing on IE 8, there are some question mark shown throughout the
> text - the issue does not occur with the other browsers.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/webfonts/Web-Fonts/issues/15.

## 

John Hooley
Blue Bridge Development
(503) 893-9181 https://www.google.com/voice#phones
http://bluebridgedev.com

**Comment by codewaresolutions** [comment]
http://mridiagnosticos.com.br/equipe.html - you can only see the problem if browsing with IE8…

**Comment by webfonts** [comment]
Hi Vivianny,

Unfortunately, I was not able to recreate your problem.  I used developer
tools to test it in IE9  by viewing the site in IE8 Standards Mode.  There
is a small possibility that with this approach it won't recreate the error,
however I've never seen developer tools render differently than the actual
browser version.

I did some searching and I found an approach that might yield some answers
or give us some clues.  In your clients browser (or IE8 if you can recreate
the issue), go to:

http://www.google.com/webfonts#UsePlace:use/Collection:Lato

Select all the font variants and review their samples and see if you see
any question marks?

Thanks,

J

On Fri, Oct 5, 2012 at 6:06 AM, codewaresolutions
notifications@github.comwrote:

> http://mridiagnosticos.com.br/equipe.html
> 
> you can only see the problem if browsing with IE8… unfortunately that’s
> the browser the customer have
> 
> thanks,
> 
> Vivianny Rodrigues
> 
> http://www.codewaresolutions.com/ http://www.codewaresolutions.com
> 
> USA: (954) 678-0268
> 
> Brasil: (19) 7821-3630 - ID: 89*122341
> 
> MSN: mailto:vivianny_rodrigues@hotmail.com
> vivianny_rodrigues@hotmail.com
> 
> Skype: codeware.solutions
> 
> From: John Hooley [mailto:notifications@github.com]
> Sent: sexta-feira, 5 de outubro de 2012 04:30
> To: webfonts/Web-Fonts
> Cc: codewaresolutions
> Subject: Re: [Web-Fonts] question marks (#15)
> 
> Hi,
> 
> Sounds like a character encoding issue. Can you post a link to an example?
> 
> Thanks,
> 
> J
> 
> On Fri, Oct 5, 2012 at 5:33 AM, codewaresolutions
> notifications@github.comwrote:
> 
> > Is web fonts joomla extension compatible with IE 8?
> > When browsing on IE 8, there are some question mark shown throughout the
> > text - the issue does not occur with the other browsers.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/webfonts/Web-Fonts/issues/15>.
> 
> ## 
> 
> John Hooley
> Blue Bridge Development
> (503) 893-9181 https://www.google.com/voice#phones
> http://bluebridgedev.com
> 
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/webfonts/Web-Fonts/issues/15#issuecomment-9167685> .
> 
> <
> https://github.com/notifications/beacon/J6T91GIPIyhU-8ti4GCGP4ICfHJR2UB1nLUYa0PVedsDqhEcNXnBFK2wLfHSlxOU.gif>
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/webfonts/Web-Fonts/issues/15#issuecomment-9174652.

## 

John Hooley
Blue Bridge Development
(503) 893-9181 https://www.google.com/voice#phones
http://bluebridgedev.com
