### ISSUE TITLE
W3C  Markup Validation

### ISSUE THREAD

**Issue by Mueh4tler** [webfonts/Web-Fonts#19]
Please can you make the component by the next release W3C valid.
I get this errors:
 Warning Line 28, Column 128: cannot generate system identifier for general entity "subset"

…,italic,bold,bolditalic,700,700italic&subset=cyrillic,latin" type="text/css" /…

✉

An entity reference was found in the document, but there is no reference by that name defined. Often this is caused by misspelling the reference name, unencoded ampersands, or by leaving off the trailing semicolon (;). The most common cause of this error is unencoded ampersands in URLs as described by the WDG in "Ampersands in URLs".

Entity references start with an ampersand (&) and end with a semicolon (;). If you want to use a literal ampersand in your document you must encode it as "&amp;" (even inside URLs!). Be careful to end entity references with a semicolon or your entity reference may get interpreted in connection with the following text. Also keep in mind that named entity references are case-sensitive; &Aelig; and &aelig; are different characters.

If this error appears in some markup generated by PHP's session handling code, this article has explanations and solutions to your problem.

Note that in most documents, errors related to entity references will trigger up to 5 separate messages from the Validator. Usually these will all disappear when the original problem is fixed.
Error Line 28, Column 128: general entity "subset" not defined and no default entity

…,italic,bold,bolditalic,700,700italic&subset=cyrillic,latin" type="text/css" /…

✉

This is usually a cascading error caused by a an undefined entity reference or use of an unencoded ampersand (&) in an URL or body text. See the previous message for further details.
Warning Line 28, Column 134: reference not terminated by REFC delimiter

…,italic,bold,bolditalic,700,700italic&subset=cyrillic,latin" type="text/css" />

✉

If you meant to include an entity that starts with "&", then you should terminate it with ";". Another reason for this error message is that you inadvertently created an entity by failing to escape an "&" character just before this text.
Warning Line 28, Column 134: reference to external entity in attribute value

…,italic,bold,bolditalic,700,700italic&subset=cyrillic,latin" type="text/css" />

✉

This is generally the sign of an ampersand that was not properly escaped for inclusion in an attribute, in a href for example. You will need to escape all instances of '&' into '&amp;'.
Error Line 28, Column 134: reference to entity "subset" for which no system identifier could be generated

…,italic,bold,bolditalic,700,700italic&subset=cyrillic,latin" type="text/css" />

✉

This is usually a cascading error caused by a an undefined entity reference or use of an unencoded ampersand (&) in an URL or body text. See the previous message for further details.
Info Line 28, Column 127: entity was defined here

…r,italic,bold,bolditalic,700,700italic&subset=cyrillic,latin" type="text/css" …

Thank you for this great extension.

Siegfried Thumfart

**Comment by webfonts** [comment]
Thanks for bringing this to my attention, I'll look into it.  It looks  
like a really simple fix, but we'll see. :)

From: Mueh4tler notifications@github.com on Sun, 25 Nov 2012 15:46:29  
+0900

> Please can you make the component by the next release W3C valid.
> I get this errors:
>  Warning Line 28, Column 128: cannot generate system identifier for  
> general entity "subset"
> 
> …,italic,bold,bolditalic,700,700italic&subset=cyrillic,latin"  
> type="text/css" /…
> 
> ✉
> 
> An entity reference was found in the document, but there is no reference  
> by that name defined. Often this is caused by misspelling the reference  
> name, unencoded ampersands, or by leaving off the trailing semicolon  
> (;). The most common cause of this error is unencoded ampersands in URLs  
> as described by the WDG in "Ampersands in URLs".
> 
> Entity references start with an ampersand (&) and end with a semicolon  
> (;). If you want to use a literal ampersand in your document you must  
> encode it as "&amp;" (even inside URLs!). Be careful to end entity  
> references with a semicolon or your entity reference may get interpreted  
> in connection with the following text. Also keep in mind that named  
> entity references are case-sensitive; &Aelig; and &aelig; are different  
> characters.
> 
> If this error appears in some markup generated by PHP's session handling  
> code, this article has explanations and solutions to your problem.
> 
> Note that in most documents, errors related to entity references will  
> trigger up to 5 separate messages from the Validator. Usually these will  
> all disappear when the original problem is fixed.
> Error Line 28, Column 128: general entity "subset" not defined and no  
> default entity
> 
> …,italic,bold,bolditalic,700,700italic&subset=cyrillic,latin"  
> type="text/css" /…
> 
> ✉
> 
> This is usually a cascading error caused by a an undefined entity  
> reference or use of an unencoded ampersand (&) in an URL or body text.  
> See the previous message for further details.
> Warning Line 28, Column 134: reference not terminated by REFC delimiter
> 
> …,italic,bold,bolditalic,700,700italic&subset=cyrillic,latin"  
> type="text/css" />
> 
> ✉
> 
> If you meant to include an entity that starts with "&", then you should  
> terminate it with ";". Another reason for this error message is that you  
> inadvertently created an entity by failing to escape an "&" character  
> just before this text.
> Warning Line 28, Column 134: reference to external entity in attribute  
> value
> 
> …,italic,bold,bolditalic,700,700italic&subset=cyrillic,latin"  
> type="text/css" />
> 
> ✉
> 
> This is generally the sign of an ampersand that was not properly escaped  
> for inclusion in an attribute, in a href for example. You will need to  
> escape all instances of '&' into '&amp;'.
> Error Line 28, Column 134: reference to entity "subset" for which no  
> system identifier could be generated
> 
> …,italic,bold,bolditalic,700,700italic&subset=cyrillic,latin"  
> type="text/css" />
> 
> ✉
> 
> This is usually a cascading error caused by a an undefined entity  
> reference or use of an unencoded ampersand (&) in an URL or body text.  
> See the previous message for further details.
> Info Line 28, Column 127: entity was defined here
> 
> …r,italic,bold,bolditalic,700,700italic&subset=cyrillic,latin"  
> type="text/css" …
> 
> Thank you for this great extension.
> 
> Siegfried Thumfart
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/webfonts/Web-Fonts/issues/19

## 

John Hooley
Blue Bridge Development
(503) 893-9181
http://bluebridgedev.com

**Comment by webfonts** [comment]
Fixed in latest version
