### ISSUE TITLE
Arabic fonts from fonts.com won't show correctly 

### ISSUE THREAD

**Issue by qotof** [webfonts/Web-Fonts#4]
Hi

i've installed the component and published the plugin,  install two fonts one English One Ararbic (RTL) , but nothing showing in the bakend preview, still showing regular font-i guess verdana- and i refreshed the page like a zillion times  !!

i'm using a subdomain-i've added it to the project- and joomla 1.7.1 with JA Erio template ,,any ideas ?

also the back end showing wierd font not sure why !!,,, site still under developments and i can send you login details

**Comment by webfonts** [comment]
Hi Qotof,

The font will not show if the domain name isn't correct, so I would recommend that you make sure and add these domains to your project:

yoursite.com
subdomain.yoursite.com
*.yoursite.com

Try this and refresh a few more times and if that doesn't work, please contact me through my website ( http://bluebridgedev.com/contact ) and we can coordinate to get information to your dev site so that I can dig around and see if there is a bug.

J

**Comment by qotof** [comment]
WOW,,, now it's working Like charm ,,thx John :)

**Comment by webfonts** [comment]
Hey Ali,

That's great!  Sometimes it takes a few minutes to update the CDN, which  
is why you didn't see changes immediately after adding the other rules.

J

From: qotof  
reply@reply.github.com  
on Tue, 20 Mar 2012 11:30:08 -0600

> On 3/19/12 6:00 PM, John Hooley wrote:
> 
> > Hi Qotof,
> > 
> > The font will not show if the domain name isn't correct, so I would  
> > recommend that you make sure and add these domains to your project:
> > 
> > yoursite.com
> > subdomain.yoursite.com
> > *.yoursite.com
> > 
> > Try this and refresh a few more times and if that doesn't work, please  
> > contact me through my website ( http://bluebridgedev.com/contact ) and  
> > we can coordinate to get information to your dev site so that I can dig  
> > around and see if there is a bug.
> > 
> > J
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/webfonts/Web-Fonts/issues/4#issuecomment-4576401
> > Dear John
> 
> thank you for your fast response ,,,i appreciate it
> 
> i did add my domain and subdomain and *.domain .com
> 
> Unfortunately Nothing happens :( even with english fonts!, I'm guessing
> something wrong in my template that override your component or plugin
> settings ..
> 
> I'm using a template from Jommlart called Erio and just upgarded to
> joomla 1.7.3
> 
> another thing happen in arabic fonts preview ,,when i display them in
> Fonts.com they were displayed correctly ( characters attached to each
> others ,unlike English,  MOST of Arabic characters are attached to each
> others otherwise the word doesn't make sense)  ,,but in the preview of
> your  component they are separated :(
> 
> sorry to bother you but i was trying to use Non safe Arabic web fonts in
> joomla for years and your wonderful component is my -my people - Hope to
> do this ,,,,any help will be HIGHLY appreciated
> 
> Ali
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/webfonts/Web-Fonts/issues/4#issuecomment-4600819

## 

John Hooley
Blue Bridge Development
(503) 893-9181
http://bluebridgedev.com
