### ISSUE TITLE
WEBFONTS image link

### ISSUE THREAD

**Issue by vladimirlisic** [webfonts/Web-Fonts#5]
Hi! How do I remove the backlink to Fonts.com? it's showing on the bottom right corner of every page...

**Comment by webfonts** [comment]
Hey GuitarMan,

For Fonts.com fonts, to remove the badge you need to have a paying
subscription:

https://webfonts.fonts.com/en-US/Subscription/SelectSubscription

Once you have set that up, you have access to all the fonts provided and
you can remove the badge by logging into the site and going to My Account >
Manage banner.  For a free account, while you cannot remove it, you can
change it's position around the edge of the screen (top,bottom, left,
right, and center along one of the edges).

Hope that helps!

J

**Comment by vladimirlisic** [comment]
Thanks, J!
