### ISSUE TITLE
Serbian latin letters won't show up...

### ISSUE THREAD

**Issue by Mzlaki** [webfonts/Web-Fonts#8]
Hi. I installed your extension without any problems. I went to Google web fonts, browsed all Latin-extended fonts with my own preview text to make sure there are the characters I need: ČŠŽĐ. When I selected the fonts back in my Joomla web fonts component, the letters won't show on my frontend, but fall back to Verdana or whatever...
Is there a way to make sure your component uses Latin extended version of the font I need?
Thanks!

**Comment by webfonts** [comment]
Hey Mzlaki,

Sorry to hear that.  In the header of your site's information is a link to
a google api.  It will look something like:

http://fonts.googleapis.com/css?family=Advent%20Pro:100,200,300,400,500,600,700

Could you tell me what it says?
Thanks,

J

On Fri, Jun 8, 2012 at 3:27 AM, Mzlaki <
reply@reply.github.com

> wrote:
> 
> Hi. I installed your extension without any problems. I went to Google web
> fonts, browsed all Latin-extended fonts with my own preview text to make
> sure there are the characters I need: ČŠŽĐ. When I selected the fonts back
> in my Joomla web fonts component, the letters won't show on my frontend,
> but fall back to Verdana or whatever...
> Is there a way to make sure your component uses Latin extended version of
> the font I need?
> Thanks!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/webfonts/Web-Fonts/issues/8

## 

John Hooley
Blue Bridge Development
(503) 893-9181 https://www.google.com/voice#phones
http://bluebridgedev.com

**Comment by Mzlaki** [comment]
Hey...
In the meantime I installed a bunch of different fonts and some of them DO show our letters. Weird. Some of them don't although they clearly contain the characters, I saw them on Google web fonts... Anyway, my problem is (half) solved. Here's the google api:

http://fonts.googleapis.com/css?family=Alegreya:400,400italic,700,700italic,900,900italic|Emblema%20One:400|Metamorphous:400|Modern%20Antiqua:regular|Oswald:300,regular,700|Titan%20One:400

**Comment by Mzlaki** [comment]
Thanks!

**Comment by webfonts** [comment]
Hey Mzlaki,

You found a bug!  Font subsets were not being included for Google fonts.  I have corrected this and if you download and install the _component_ from the downloads page, you should see the extended character set working.

Thanks for submitting this,

J

**Comment by Mzlaki** [comment]
Hey, I'm glad to help... :)
Thank you for offering this amazing free component! :)

**Comment by webfonts** [comment]
Hey Mzlaki,

Glad to help.  While I appreciated the opportunity to build this extension,
it was Fonts.com who hired me and bank rolled it.  You might consider
popping over to their site and leaving them a thank-you message via the
feedback button. :)

J

On Tue, Jun 12, 2012 at 3:59 PM, Mzlaki <
reply@reply.github.com

> wrote:
> 
> Hey, I'm glad to help... :)
> Thank you for offering this amazing free component! :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/webfonts/Web-Fonts/issues/8#issuecomment-6264236

## 

John Hooley
Blue Bridge Development
(503) 893-9181 https://www.google.com/voice#phones
http://bluebridgedev.com
