### ISSUE TITLE
Work perfect but, in log; Error, PHP Notice Undefined Propperty and plus?

### ISSUE THREAD

**Issue by Chacapamac** [webfonts/Web-Fonts#9]
## I got that in my php log

 PHP Notice:  Undefined property: stdClass::$Publish in /Applications/MAMP/htdocs/xxxxxxxxxxx/administrator/components/com_webfonts/helpers/responses.php on line 57

PHP Warning:  First parameter must either be an object or the name of an existing class in /Applications/MAMP/htdocs/xxxxxxxxxxx/administrator/components/com_webfonts/helpers/responses.php on line 45
## PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/xxxxxxxxxxx/administrator/components/com_webfonts/helpers/responses.php on line 31

On Mamp — Joomla 2.5.6

I got those selectors

.module-title .title span 

h1 span

h1

h2

**Comment by webfonts** [comment]
Hey Chacapamac, this code is a little loose and I will tighten it down and post an update here tomorrow.

**Comment by webfonts** [comment]
Hey Chacapamac, I'm not able to reproduce those errors/warning.  Do you get them in in your production environment?

**Comment by Chacapamac** [comment]
Well, I just reopen the site and refresh a couple of time — Nothing in the log. Weird,
 I think you can close this

**Comment by webfonts** [comment]
Hey Chacapamac,

Actually, your lack of errors is a telling symptom and I believe I know
what caused your original errors.  If I'm right, it's not something in your
environment and just something that doesn't happen every time the extension
is used.  I'll do an update in the next couple of days with this and the
important change.

J

**Comment by Chacapamac** [comment]
Thank’s — Give you an excellent review at the JED — Really simple and flexible extension... Good work —Are you doing on demand component and addon to Joomla?
